# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Il Veneto che vogliamo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.venetochevogliamo.it" # the base hostname & protocol for your site, e.g. http://example.com

# Collections
collections_dir: content
collections:
  mozioni:
    output: true
    permalink: /mozioni/:title/
    sort_by: date
  # eventi:
  #   sort_by: date

# Feed RSS
feed:
  collections:
    - mozioni

navbar:
  - title: "Che cos'è"
    url: /#about
  - title: "Province"
    url: /province/
  - title: "Mozioni"
    url: /mozioni/
  - title: "Calendario"
    url: /calendario/
  - title: "Appello"
    url: /progetto-politico/

# Social Network
social_network:
  - name: Facebook
    url: https://www.facebook.com/venetochevogliamo/
    fa-icon: fab fa-facebook
  - name: Twitter
    url: https://www.twitter.com/venetocvogliamo/
    fa-icon: fab fa-twitter
  - name: Telegram
    url: https://t.me/ilvenetochevogliamo/
    fa-icon: fab fa-telegram
  - name: Instagram
    url: https://www.instagram.com/ilvenetochevogliamo/
    fa-icon: fab fa-instagram
  # - name: Feed RSS
  #   url: #
  #   fa-icon: fas fa-rss

# Jekyll SEO
twitter: 
  username: venetocvogliamo
  card: summary
lang: it_IT

social:
  name: Il Veneto che vogliamo
  links:
    - https://twitter.com/venetocvogliamo
    - https://www.facebook.com/venetochevogliamo
    - https://t.me/ilvenetochevogliamo/
    - https://www.instagram.com/ilvenetochevogliamo/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/il-veneto-che-vogliamo-fb.png
  - scope:
      path: ""
      type: "mozioni"
    values:
      layout: "post"

google_analytics: UA-143417190-1
privacy_policy_url: https://www.iubenda.com/privacy-policy/40606125

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/functions/
  - src/actions/
  - lambda
